source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.1.3"

gem "bcrypt", "~> 3.1.7"
gem "bootsnap", require: false
gem "honeybadger"
gem "image_processing", "~> 1.2"
gem "importmap-rails", ">= 2.0.0"
gem "inline_svg"
gem "jbuilder", ">= 2.12.0"
gem "measured-rails", ">= 3.0.0"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "redis", ">= 4.0.1"
gem "sprockets-rails"
gem "standard"
gem "stimulus-rails", ">= 1.3.1"
gem "tailwindcss-rails", ">= 2.0.32"
gem "turbo-rails", ">= 2.0.0"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "pry-rails"
  gem "web-console"
end

group :test do
  gem "capybara", ">= 3.40.0"
  gem "selenium-webdriver"
end
